# Fly.io deployment configuration
# fly.toml

app = "codemate-research"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  PYTHONPATH = "/app"
  FLASK_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[http_service.checks]]
  grace_period = "60s"
  interval = "30s"
  method = "GET"
  timeout = "10s"
  path = "/ready"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # Start with 1GB (free tier)