# Railway Deployment Configuration
# railway.toml

[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/ready"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "8080"
PYTHONPATH = "/app"
FLASK_ENV = "production"